### ISSUE TITLE
网络唤醒

### ISSUE THREAD

**Issue by sunO2** [3Alan/Hackintosh-i5-10400-B460M-MORTAR-WIFI#13]
你好 麻烦问下 你那边网络唤醒能用不 WOL 网络唤醒
并且麻烦帮忙看下 设置---> 节能 
你那边显示的是 
    1.唤醒以供网络访问
    2.唤醒以供WIFI 访问
这两个中的哪个呢
     谢谢

**Comment by 3Alan** [comment]
我不太清楚网络唤醒是什么
节能里显示的是：唤醒以供网络访问
