### ISSUE TITLE
你好，请问下，可以显示cpu转速吗

### ISSUE THREAD

**Issue by Minor-fun** [3Alan/Hackintosh-i5-10400-B460M-MORTAR-WIFI#6]
![截屏2021-07-13 下午11 44 03](https://user-images.githubusercontent.com/45744798/125482976-193c3fb4-ef7a-4d37-9cc6-fe5b7c2d4978.png)
我用istat menus 监控不到cpu的转速，

**Comment by 3Alan** [comment]
不太清楚，没用过这个软件
